version: 0.0
os: linux
files:
        - source: ./Reactjs-DEV-CICD/BuildArtif/build
          destination: /usr/share/nginx/build/
hooks:
       BeforeInstall:
                - location: scripts/nginx_stop.sh
                  timeout: 300
                  runas: root
       AfterInstall:
                - location: scripts/nginx_start.sh
                  timeout: 300
                  runas: root
